// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';

import { useEffect, useState } from 'react';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { useAuth } from '@/firebase/provider';

interface UseUserResult {
  user: User | null;
  loading: boolean;
}

/**
 * A React hook to get the current authenticated user from Firebase.
 *
 * @returns {UseUserResult} An object containing the user and loading state.
 *
 * @example
 * ```tsx
 * import { useUser } from '@/firebase';
 *
 * function UserProfile() {
 *   const { user, loading } = useUser();
 *
 *   if (loading) {
 *     return <p>Loading...</p>;
 *   }
 *
 *   if (!user) {
 *     return <p>Please sign in.</p>;
 *   }
 *
 *   return (
 *     <div>
 *       <h1>Welcome, {user.displayName}!</h1>
 *       <img src={user.photoURL} alt="Profile" />
 *     </div>
 *   );
 * }
 * ```
 */
export function useUser(): UseUserResult {
  const auth = useAuth();
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!auth) {
      // If auth is not yet available, we are in a loading state.
      // The provider will re-render when auth is initialized.
      setLoading(true);
      return;
    }

    const unsubscribe = onAuthStateChanged(
      auth,
      (firebaseUser) => {
        setUser(firebaseUser);
        setLoading(false);
      },
      (error) => {
        console.error('Auth state change error:', error);
        setUser(null);
        setLoading(false);
      }
    );

    // Cleanup subscription on unmount
    return () => unsubscribe();
  }, [auth]);

  return { user, loading };
}
