// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';

import { useEffect, useState, useRef } from 'react';
import {
  onSnapshot,
  type DocumentData,
  type DocumentReference,
  type Unsubscribe,
  type WithFieldValue,
  type SnapshotOptions,
} from 'firebase/firestore';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

/**
 * Represents the state of a Firestore document listener.
 * @template T The type of the document.
 */
interface UseDocResult<T> {
  data: T | null;
  loading: boolean;
  error: Error | null;
}

/**
 * A generic hook to listen for real-time updates to a single Firestore document.
 * It simplifies subscribing to a document and managing the component's state.
 *
 * **Crucially, you must memoize the `docRef` you pass to this hook,
 * typically with `useMemo` or `useMemoFirebase`, to prevent infinite re-renders.**
 *
 * @template T The expected type of the document data.
 * @param {DocumentReference<T> | null} docRef The Firestore `DocumentReference` to listen to.
 *   The hook will not perform any action if the reference is `null` or `undefined`.
 * @param {SnapshotOptions} [options] Options to control snapshot behavior.
 * @returns {UseDocResult<T>} An object containing `data`, `loading`, and `error` states.
 *
 * @example
 * ```tsx
 * import { useMemo } from 'react';
 * import { doc } from 'firebase/firestore';
 * import { useDoc, useFirestore, useUser } from '@/firebase';
 *
 * interface UserProfile {
 *   id: string;
 *   displayName: string;
 *   email: string;
 * }
 *
 * function UserProfileDetails() {
 *   const firestore = useFirestore();
 *   const { user } = useUser();
 *
 *   // Memoize the document reference.
 *   const userDocRef = useMemo(() => {
 *     if (!firestore || !user) return null;
 *     return doc(firestore, 'users', user.uid) as DocumentReference<UserProfile>;
 *   }, [firestore, user]);
 *
 *   const { data: userProfile, loading, error } = useDoc(userDocRef);
 *
 *   if (loading) return <p>Loading profile...</p>;
 *   if (error) return <p>Error: {error.message}</p>;
 *   if (!userProfile) return <p>No profile found.</p>;
 *
 *   return <h1>Welcome, {userProfile.displayName}!</h1>;
 * }
 * ```
 */
export function useDoc<T extends DocumentData>(
  docRef: DocumentReference<T> | null | undefined,
  options?: SnapshotOptions
): UseDocResult<T> {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  // Use the document path as a key to detect when the reference changes.
  const lastDocPath = useRef<string | null>(null);

  useEffect(() => {
    if (!docRef) {
      setLoading(false);
      setData(null);
      return;
    }
    
    if (lastDocPath.current === docRef.path) {
        return; // Document reference hasn't changed.
    }
    lastDocPath.current = docRef.path;

    setLoading(true);
    setError(null);

    const unsubscribe: Unsubscribe = onSnapshot(
      docRef,
      options || {},
      (snapshot) => {
        if (snapshot.exists()) {
          setData({ ...snapshot.data(), id: snapshot.id } as WithFieldValue<T>);
        } else {
          setData(null);
        }
        setLoading(false);
      },
      (err) => {
        console.error('useDoc snapshot error:', err);
        setError(err);
        setLoading(false);
        
        // Emit a detailed permission error for better debugging.
        const permissionError = new FirestorePermissionError({
            path: docRef.path,
            operation: 'get',
        });
        errorEmitter.emit('permission-error', permissionError);
      }
    );

    // Cleanup subscription on unmount or when docRef changes.
    return () => {
      unsubscribe();
    };
  }, [docRef, options]); // `options` is included as a dependency

  return { data, loading, error };
}
