// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';

import { useEffect, useState, useMemo, useRef } from 'react';
import {
  onSnapshot,
  query,
  where,
  orderBy,
  limit,
  startAt,
  endAt,
  type DocumentData,
  type Query,
  type Unsubscribe,
  type WithFieldValue,
  type SnapshotOptions,
  type QueryConstraint,
} from 'firebase/firestore';
import { useFirestore } from '@/firebase/provider';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

/**
 * Represents the state of a Firestore collection listener.
 * @template T The type of the documents in the collection.
 */
interface UseCollectionResult<T> {
  data: T[] | null;
  loading: boolean;
  error: Error | null;
}

/**
 * A generic hook to listen for real-time updates to a Firestore collection.
 * It simplifies the process of subscribing to a collection query and managing
 * the component's state (data, loading, error).
 *
 * **Crucially, you must memoize the `query` or `constraints` you pass to this hook,
 * typically with `useMemo` or `useMemoFirebase`, to prevent infinite re-renders.**
 *
 * @template T The expected type of the documents in the collection.
 * @param {Query<T> | null} query The Firestore `Query` object to listen to. The hook will not
 *   do anything if the query is `null` or `undefined`.
 * @param {SnapshotOptions} [options] Options to control snapshot behavior, like `includeMetadataChanges`.
 * @returns {UseCollectionResult<T>} An object containing `data`, `loading`, and `error` states.
 *
 * @example
 * ```tsx
 * import { useMemo } from 'react';
 * import { collection, query, where, orderBy } from 'firebase/firestore';
 * import { useCollection, useFirestore, useUser } from '@/firebase';
 *
 * interface Task {
 *   id: string;
 *   title: string;
 *   completed: boolean;
 *   createdAt: Timestamp;
 * }
 *
 * function TaskList() {
 *   const firestore = useFirestore();
 *   const { user } = useUser();
 *
 *   // Memoize the query to prevent re-creating it on every render.
 *   const tasksQuery = useMemo(() => {
 *     if (!firestore || !user) return null;
 *     return query(
 *       collection(firestore, 'tasks') as Query<Task>,
 *       where('userId', '==', user.uid),
 *       orderBy('createdAt', 'desc')
 *     );
 *   }, [firestore, user]);
 *
 *   const { data: tasks, loading, error } = useCollection(tasksQuery);
 *
 *   if (loading) return <p>Loading tasks...</p>;
 *   if (error) return <p>Error: {error.message}</p>;
 *
 *   return (
 *     <ul>
 *       {tasks?.map(task => (
 *         <li key={task.id}>{task.title}</li>
 *       ))}
 *     </ul>
 *   );
 * }
 * ```
 */
export function useCollection<T extends DocumentData>(
  q: Query<T> | null | undefined,
  options?: SnapshotOptions
): UseCollectionResult<T> {
  const [data, setData] = useState<T[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  // Keep track of the query to avoid re-subscribing to the same query.
  // This is a simple string comparison of the query's internal `_key`.
  const lastQueryKey = useRef<string | null>(null);

  useEffect(() => {
    // If the query is not ready, do nothing.
    if (!q) {
      setLoading(false);
      setData(null);
      return;
    }
    
    // @ts-ignore - _key is an internal but stable property of a Firestore query
    const currentQueryKey = q._key;
    if (lastQueryKey.current === currentQueryKey) {
      return; // Query hasn't changed, no need to re-subscribe
    }
    lastQueryKey.current = currentQueryKey;

    setLoading(true);
    setError(null);

    const unsubscribe: Unsubscribe = onSnapshot(
      q,
      options || {},
      (snapshot) => {
        const docs = snapshot.docs.map(
          (doc) => ({ ...doc.data(), id: doc.id } as WithFieldValue<T>)
        );
        setData(docs);
        setLoading(false);
      },
      (err) => {
        console.error('useCollection snapshot error:', err);
        setError(err);
        setLoading(false);
        
        // Emit a detailed permission error for better debugging.
        const permissionError = new FirestorePermissionError({
            // @ts-ignore - _path is internal but useful
            path: q.path || 'unknown collection',
            operation: 'list',
        });
        errorEmitter.emit('permission-error', permissionError);
      }
    );

    // Cleanup subscription on unmount or when the query changes.
    return () => {
      unsubscribe();
    };
  }, [q, options]); // `options` is included as a dependency

  return { data, loading, error };
}
