// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';

import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react';
import { FirebaseProvider, type FirebaseContextType } from './provider';
import { initializeFirebase } from '.';

/**
 * A React provider that ensures Firebase is initialized only once on the client-side.
 * It memoizes the Firebase app, Firestore, and Auth instances to prevent re-initialization
 * on re-renders, which is crucial for performance and avoiding unexpected side effects.
 *
 * This provider should wrap your application's root component (e.g., in `layout.tsx`).
 *
 * @param {React.PropsWithChildren} props The children components to render.
 *
 * @example
 * ```tsx
 * // in src/app/layout.tsx
 * import { FirebaseClientProvider } from '@/firebase';
 *
 * export default function RootLayout({ children }: { children: React.ReactNode }) {
 *   return (
 *     <html lang="en">
 *       <body>
 *         <FirebaseClientProvider>
 *           {children}
 *         </FirebaseClientProvider>
 *       </body>
 *     </html>
 *   );
 * }
 * ```
 */
export function FirebaseClientProvider({
  children,
}: React.PropsWithChildren<{}>) {
  // Use state to hold the initialized Firebase context.
  // This prevents re-running initialization on every render.
  const [firebaseContext, setFirebaseContext] =
    useState<FirebaseContextType | null>(null);

  useEffect(() => {
    // This async function initializes Firebase and sets the context.
    const initFirebase = async () => {
      const context = await initializeFirebase();
      setFirebaseContext(context);
    };
    
    initFirebase();

    // Note: We don't need a cleanup function here as we want Firebase
    // to remain initialized for the lifetime of the client session.
  }, []); // Empty dependency array ensures this runs only once.

  // The FirebaseProvider requires a valid context. We render children only
  // after the async initialization is complete.
  // You can add a loading spinner here if initialization takes a noticeable amount of time.
  if (!firebaseContext) {
    return null; // Or a loading component
  }

  return (
    <FirebaseProvider {...firebaseContext}>{children}</FirebaseProvider>
  );
}
