// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
/**
 * This file exports the configuration for the Firebase app.
 *
 * It is used by the `initializeFirebase` function in `src/firebase/index.ts` to connect to your Firebase project.
 * This object is safe to be exposed on the client-side. Security is handled by Firebase Security Rules.
 *
 * For more information on Firebase configuration, see the official documentation:
 * https://firebase.google.com/docs/web/setup#config-object
 */

// This configuration is dynamically generated by Firebase Studio.
// Do not modify this file manually.
export const firebaseConfig = {"apiKey":"your-api-key","authDomain":"your-project-id.firebaseapp.com","projectId":"your-project-id","storageBucket":"your-project-id.appspot.com","messagingSenderId":"your-sender-id","appId":"your-app-id","measurementId":"your-measurement-id"};
