// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
/**
 * This file exports the configuration for the Firebase app.
 *
 * It is used by the `initializeFirebase` function in `src/firebase/index.ts` to connect to your Firebase project.
 * This object is safe to be exposed on the client-side. Security is handled by Firebase Security Rules.
 */

export const firebaseConfig = {
  // IMPORTANT: Replace the placeholder below with your actual API Key from the Firebase Console
  // Settings -> Project Settings -> General -> Your apps -> SDK setup and configuration
  apiKey: "AIzaSy-placeholder-key-for-your-project",
  authDomain: "bharat-suchana-app.firebaseapp.com",
  projectId: "bharat-suchana-app",
  storage_bucket: "bharat-suchana-app.appspot.com",
  messagingSenderId: "123456789012",
  appId: "1:123456789012:web:abcdef1234567890",
  measurementId: "G-ABCDEF1234"
};
