// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
type EventMap = {
  'permission-error': (error: Error) => void;
  // Add other event types here if needed
};

type EventName = keyof EventMap;

/**
 * A simple, type-safe event emitter for handling specific application events,
 * such as Firebase permission errors. This allows different parts of the application
 * to communicate without being directly coupled.
 *
 * It is primarily used to emit `FirestorePermissionError` instances from data
 * mutation functions, which are then caught by a listener (e.g., `FirebaseErrorListener`)
 * to display a developer-friendly error in the Next.js overlay during development.
 */
class ErrorEmitter {
  private listeners: {
    [K in EventName]?: Array<EventMap[K]>;
  } = {};

  /**
   * Registers an event listener for a given event name.
   * @param eventName The name of the event to listen for.
   * @param listener The callback function to execute when the event is emitted.
   */
  on<E extends EventName>(eventName: E, listener: EventMap[E]) {
    if (!this.listeners[eventName]) {
      this.listeners[eventName] = [];
    }
    this.listeners[eventName]!.push(listener);
  }

  /**
   * Unregisters an event listener for a given event name.
   * @param eventName The name of the event.
   * @param listener The callback function to remove.
   */
  off<E extends EventName>(eventName: E, listener: EventMap[E]) {
    if (!this.listeners[eventName]) {
      return;
    }
    const index = this.listeners[eventName]!.indexOf(listener);
    if (index > -1) {
      this.listeners[eventName]!.splice(index, 1);
    }
  }

  /**
   * Emits an event, calling all registered listeners for that event.
   * @param eventName The name of the event to emit.
   * @param data The data to pass to the listeners.
   */
  emit<E extends EventName>(eventName: E, data: Parameters<EventMap[E]>[0]) {
    if (!this.listeners[eventName]) {
      return;
    }
    // Type assertion to ensure `listener` has the correct signature for the event.
    this.listeners[eventName]!.forEach((listener) => (listener as (d: typeof data) => void)(data));
  }
}

/**
 * A global singleton instance of the `ErrorEmitter`.
 * Import this instance to emit or listen for events throughout the application.
 */
export const errorEmitter = new ErrorEmitter();
