// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
/**
 * Defines the context for a Firestore security rule denial.
 * This information is used to construct a detailed error message
 * that helps developers debug their security rules.
 */
export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  requestResourceData?: any;
};

const FIRESTORE_PERMISSION_ERROR_NAME = 'FirestorePermissionError';

/**
 * A custom error class for Firestore permission-denied errors.
 *
 * This class is designed to be thrown from a `.catch()` block when a
 * Firestore operation (like `setDoc`, `updateDoc`, `addDoc`) fails due to
 * security rules. It captures detailed context about the failed operation,
 * which can then be displayed in a developer-friendly format (e.g., in the
 * Next.js error overlay) to significantly speed up debugging of security rules.
 *
 * The `FirebaseErrorListener` component is responsible for catching these
 * errors and presenting them.
 *
 * @example
 * ```ts
 * import { doc, setDoc } from 'firebase/firestore';
 * import { errorEmitter } from '@/firebase/error-emitter';
 * import { FirestorePermissionError } from '@/firebase/errors';
 * import { useFirestore } from '@/firebase';
 *
 * function updateDocument(docId: string, data: any) {
 *   const db = useFirestore();
 *   const docRef = doc(db, 'myCollection', docId);
 *
 *   setDoc(docRef, data, { merge: true })
 *     .catch(async (serverError) => {
 *       // The Firestore SDK threw a generic "Missing or insufficient permissions" error.
 *       // We create our custom, context-rich error.
 *       const permissionError = new FirestorePermissionError({
 *         path: docRef.path,
 *         operation: 'update',
 *         requestResourceData: data,
 *       });
 *
 *       // Emit the error so a listener can display it.
 *       errorEmitter.emit('permission-error', permissionError);
 *     });
 * }
 * ```
 */
export class FirestorePermissionError extends Error {
  /**
   * The detailed context of the Firestore operation that was denied.
   */
  public readonly context: SecurityRuleContext;

  constructor(context: SecurityRuleContext) {
    const operation = context.operation.toUpperCase();
    const message =
      `Firestore Permission Denied: The ${operation} operation at path '${context.path}' was denied by your security rules. ` +
      `Check the Next.js error overlay for a detailed breakdown of the request context, including the user's auth state and the data being sent. ` +
      `This will help you debug and refine your Firestore security rules.`;

    super(message);
    this.name = FIRESTORE_PERMISSION_ERROR_NAME;
    this.context = context;

    // This ensures the stack trace is captured correctly in V8 environments (like Node.js and Chrome)
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, FirestorePermissionError);
    }
  }

  /**
   * Type guard to check if an error is an instance of `FirestorePermissionError`.
   * This is more reliable than `instanceof` across different modules or if the
   * class definition is duplicated.
   *
   * @param error The error object to check.
   * @returns `true` if the error is a `FirestorePermissionError`, `false` otherwise.
   */
  public static is(error: any): error is FirestorePermissionError {
    return error?.name === FIRESTORE_PERMISSION_ERROR_NAME;
  }
}
