// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
import { initializeApp, getApp, getApps, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore, enableIndexedDbPersistence } from 'firebase/firestore';
import { firebaseConfig } from './config';

import { useCollection } from './firestore/use-collection';
import { useDoc } from './firestore/use-doc';
import { useUser } from './auth/use-user';
import {
  FirebaseProvider,
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
} from './provider';
import { FirebaseClientProvider } from './client-provider';

/**
 * Initializes and returns the Firebase app, Firestore, and Auth instances.
 * It ensures that Firebase is initialized only once (idempotent).
 * It also enables offline persistence for Firestore.
 *
 * This function is called by `FirebaseClientProvider` to set up the global
 * Firebase context for the application.
 *
 * @returns An object containing the initialized `firebaseApp`, `firestore`, and `auth` instances.
 */
export async function initializeFirebase(): Promise<{
  firebaseApp: FirebaseApp;
  firestore: Firestore;
  auth: Auth;
}> {
  // Check if Firebase has already been initialized.
  const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();

  const firestore = getFirestore(app);
  const auth = getAuth(app);

  try {
    // This enables offline persistence. Data will be cached locally
    // so the app can work even when the user is offline.
    await enableIndexedDbPersistence(firestore);
  } catch (err: any) {
    if (err.code === 'failed-precondition') {
      // This can happen if multiple tabs are open.
      console.warn(
        'Firebase offline persistence could not be enabled: Multiple tabs open.'
      );
    } else if (err.code === 'unimplemented') {
      // This can happen in browsers that do not support IndexedDB.
      console.warn(
        'Firebase offline persistence is not available in this browser.'
      );
    }
  }


  return { firebaseApp: app, firestore, auth };
}

export {
  // Core initialization and providers
  FirebaseProvider,
  FirebaseClientProvider,

  // High-level hooks for data and user management
  useCollection,
  useDoc,
  useUser,

  // Low-level hooks for accessing Firebase service instances
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
};
