
// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
import { initializeApp, getApp, getApps, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { firebaseConfig } from './config';

import { useCollection } from './firestore/use-collection';
import { useDoc } from './firestore/use-doc';
import { useUser } from './auth/use-user';
import {
  FirebaseProvider,
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
} from './provider';
import { FirebaseClientProvider } from './client-provider';

/**
 * Initializes and returns the Firebase app, Firestore, and Auth instances.
 * It ensures that Firebase is initialized only once (idempotent).
 *
 * This function is called by `FirebaseClientProvider` to set up the global
 * Firebase context for the application.
 *
 * @returns An object containing the initialized `firebaseApp`, `firestore`, and `auth` instances.
 */
export function initializeFirebase(): {
  firebaseApp: FirebaseApp;
  firestore: Firestore;
  auth: Auth;
} {
  // Check if Firebase has already been initialized.
  const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();

  const firestore = getFirestore(app);
  const auth = getAuth(app);

  return { firebaseApp: app, firestore, auth };
}

export {
  // Core initialization and providers
  FirebaseProvider,
  FirebaseClientProvider,

  // High-level hooks for data and user management
  useCollection,
  useDoc,
  useUser,

  // Low-level hooks for accessing Firebase service instances
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
};
