// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';

import React, { createContext, useContext, type ReactNode } from 'react';
import type { FirebaseApp } from 'firebase/app';
import type { Auth } from 'firebase/auth';
import type { Firestore } from 'firebase/firestore';
import { FirebaseErrorListener } from '@/components/FirebaseErrorListener';

/**
 * Defines the shape of the context object that provides Firebase services.
 */
export interface FirebaseContextType {
  firebaseApp: FirebaseApp | null;
  firestore: Firestore | null;
  auth: Auth | null;
}

/**
 * React context for providing Firebase services throughout the application.
 * This context should be initialized with the `FirebaseProvider`.
 */
const FirebaseContext = createContext<FirebaseContextType>({
  firebaseApp: null,
  firestore: null,
  auth: null,
});

/**
 * A React provider component that makes Firebase services (app, firestore, auth)
 * available to all child components via the `useFirebase`, `useFirestore`, and `useAuth` hooks.
 *
 * This component is typically used inside `FirebaseClientProvider`, which ensures
 * that Firebase is initialized only once on the client.
 *
 * @param {object} props The properties for the component.
 * @param {FirebaseContextType} props.value An object containing the Firebase services.
 * @param {ReactNode} props.children The child components to render.
 *
 * @example
 * ```tsx
 * // This is an example of how FirebaseProvider is used inside FirebaseClientProvider.
 * // You generally won't use this component directly.
 *
 * const { firebaseApp, firestore, auth } = initializeFirebase();
 *
 * <FirebaseProvider value={{ firebaseApp, firestore, auth }}>
 *   <App />
 * </FirebaseProvider>
 * ```
 */
export const FirebaseProvider: React.FC<React.PropsWithChildren<FirebaseContextType>> = ({
  children,
  firebaseApp,
  firestore,
  auth
}) => {
  const value = { firebaseApp, firestore, auth };

  return (
    <FirebaseContext.Provider value={value}>
      {children}
      {process.env.NODE_ENV === 'development' && <FirebaseErrorListener />}
    </FirebaseContext.Provider>
  );
};

// --- Consumer Hooks ---

/**
 * A hook to access the entire Firebase context, including the app, Firestore, and Auth instances.
 * Throws an error if used outside of a `FirebaseProvider`.
 * @returns {FirebaseContextType} The Firebase context.
 */
export function useFirebase(): FirebaseContextType {
  const context = useContext(FirebaseContext);
  if (context === undefined) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
}

/**
 * A hook to access the Firebase App instance.
 * @returns {FirebaseApp} The Firebase App instance.
 */
export function useFirebaseApp(): FirebaseApp {
  const { firebaseApp } = useFirebase();
  if (!firebaseApp) {
    throw new Error('Firebase App not initialized. Make sure you are using FirebaseProvider.');
  }
  return firebaseApp;
}

/**
 * A hook to access the Firestore database instance.
 * @returns {Firestore} The Firestore instance.
 */
export function useFirestore(): Firestore {
  const { firestore } = useFirebase();
  if (!firestore) {
    throw new Error('Firestore not initialized. Make sure you are using FirebaseProvider.');
  }
  return firestore;
}

/**
 * A hook to access the Firebase Auth instance.
 * @returns {Auth} The Firebase Auth instance.
 */
export function useAuth(): Auth {
  const { auth } = useFirebase();
  if (!auth) {
    throw new Error('Firebase Auth not initialized. Make sure you are using FirebaseProvider.');
  }
  return auth;
}
