// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';

import { useEffect } from 'react';
import { errorEmitter } from '@/firebase/error-emitter';
import { useToast } from '@/hooks/use-toast';

/**
 * A client component that listens for Firebase permission errors and displays a toast notification.
 * This is intended for development purposes to provide immediate feedback on security rule violations.
 *
 * It should be placed within your main layout or a top-level provider.
 */
export function FirebaseErrorListener() {
  const { toast } = useToast();

  useEffect(() => {
    const handleError = (error: Error) => {
      console.error('Firebase Permission Error:', error);

      // Throw the error to make it visible in the Next.js development overlay
      // This provides a richer debugging experience than just a console log.
      throw error;
    };

    // Listen for 'permission-error' events
    errorEmitter.on('permission-error', handleError);

    // Clean up the listener when the component unmounts
    return () => {
      errorEmitter.off('permission-error', handleError);
    };
  }, [toast]);

  // This component does not render anything itself
  return null;
}
